import{useEffect,useMemo,useState}from"react";import styles from"./Home.module.css";
type Props={content:any};
function Icon({kind}:{kind:string}){const p=kind==="check"?"M5 12l4 4L19 6":kind==="copy"?"M8 8h10v10H8z M5 5h10v3":kind==="edit"?"M4 20l4-1 11-11-3-3L5 16l-1 4z":"M5 12h14m-5-5 5 5-5 5";return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8"><path d={p}/></svg>}
function CopyInstallButton({location}:{location:string}){const[copied,setCopied]=useState(false);const command="npm i -g agentplane";async function copy(){await navigator.clipboard.writeText(command);setCopied(true);(window as any).gtag?.("event","copy_install_click",{event_category:"home",location});window.setTimeout(()=>setCopied(false),1600)}return <button className={`${styles.installButton} ${copied?styles.installButtonCopied:""}`} type="button" onClick={()=>void copy()}><code>{copied?"Copied to clipboard":command}</code><span className={styles.copyIcon}><Icon kind="copy"/></span></button>}
const tones:Record<string,string>={blue:styles.toneBlue,violet:styles.toneViolet,green:styles.toneGreen,coral:styles.toneCoral};
export default function Home({content}:Props){useEffect(()=>{document.documentElement.classList.add("agentplane-home");document.body.classList.add("agentplane-home");return()=>document.body.classList.remove("agentplane-home")},[]);
const[activeId,setActiveId]=useState(content.controlLoop.steps[0]?.id);const activeStep=useMemo(()=>content.controlLoop.steps.find((s:any)=>s.id===activeId)??content.controlLoop.steps[0],[activeId,content.controlLoop.steps]);
return <main className={styles.page}>
<section className={styles.hero}><div className={styles.heroInner}><div className={styles.heroCopy}><p className={styles.kicker}>{content.hero.eyebrow}</p><h1 aria-label={content.hero.title}>{content.hero.titleLines.map((l:string)=><span key={l}>{l}</span>)}</h1><p className={styles.lede}>{content.hero.subtitle}</p><div className={styles.ctaGroup}><a className={styles.buttonPrimary} href={content.links.quickstart}>Start in your repository</a><CopyInstallButton location="hero"/></div><p className={styles.trust}>{content.hero.trustLine}</p></div>
<article className={styles.heroReceipt}><header className={styles.receiptHeader}><div><span className={styles.receiptType}>Execution receipt</span><p>{content.receipt.id}</p></div><span className={styles.receiptAuthority}>Authority + proof</span></header><div className={styles.receiptTitle}><p>WorkOrder</p><h2>{content.receipt.objective}</h2></div><dl className={styles.receiptRows}>{content.receipt.rows.map((r:any[],i:number)=><div key={r[0]} className={styles.receiptRow}><dt>{r[0]}</dt><dd>{r[1]}</dd><dd className={styles.receiptDetail}>{i>=2?<span><Icon kind="check"/></span>:null}{r[2]}</dd></div>)}</dl><footer className={styles.receiptFooter}><span className={styles.verifiedMark}><Icon kind="check"/></span><div><strong>Durable record in Git</strong><p>Task state, ACR, and evidence manifest stay reviewable with the code.</p></div><code>{content.receipt.commit}</code></footer></article></div></section>
<section className={`${styles.section} ${styles.reveal}`}><div className={styles.splitSection}><div className={styles.sectionIntro}><p className={styles.kicker}>{content.authorityGap.eyebrow}</p><h2>{content.authorityGap.title}</h2><p>{content.authorityGap.text}</p></div><div className={styles.diffPanel}><header><code>git diff -- src/parser/token.ts</code></header><pre><code><span className={styles.diffMeta}>@@ -142,7 +142,7 @@ parse_token(...)</span>{"\n"}<span className={styles.diffRemove}>- if (c == EOF &amp;&amp; !in_string) &#123;</span>{"\n"}<span className={styles.diffAdd}>+ if (c == EOF &amp;&amp; !in_string &amp;&amp; !escaped) &#123;</span>{"\n"}{"    return ERROR_UNTERMINATED;\n  }"}</code></pre><footer><strong>Missing proof</strong><p>No record of scope, allowed effects, approver, or independent verification.</p></footer></div></div></section>
<section className={`${styles.section} ${styles.loopSection} ${styles.reveal}`}><div className={styles.sectionIntroWide}><p className={styles.kicker}>{content.controlLoop.eyebrow}</p><h2>{content.controlLoop.title}</h2><p>{content.controlLoop.text}</p></div><div className={styles.loopGrid}>{content.controlLoop.steps.map((s:any,i:number)=><div className={styles.loopCell} key={s.id}><button className={`${styles.loopStep} ${tones[s.tone]} ${s.id===activeId?styles.loopStepActive:""}`} onClick={()=>setActiveId(s.id)}><span className={styles.stepNumber}>0{i+1}</span><span className={styles.stepIcon}><Icon kind={s.icon==="verify"?"check":s.icon==="record"?"copy":s.icon==="authorize"?"edit":"arrow"}/></span><strong>{s.title}</strong><span className={styles.stepText}>{s.text}</span></button>{i<content.controlLoop.steps.length-1?<span className={styles.loopArrow}><Icon kind="arrow"/></span>:null}</div>)}</div>{activeStep?<div className={`${styles.loopEvidence} ${tones[activeStep.tone]}`}><span>{activeStep.title}</span><strong>{activeStep.evidence}</strong><code>{activeStep.artifact}</code></div>:null}</section>
<section className={`${styles.section} ${styles.proofSection} ${styles.reveal}`}><div className={styles.sectionIntroWide}><p className={styles.kicker}>{content.durableProof.eyebrow}</p><h2>{content.durableProof.title}</h2><p>{content.durableProof.text}</p></div><div className={styles.proofLedger}><header><div><code>{content.durableProof.commit}</code><strong>{content.durableProof.summary}</strong></div><span className={styles.proofStatus}><Icon kind="check"/> verified</span></header><div className={styles.proofBody}><ul className={styles.fileList}>{content.durableProof.files.map((f:string)=><li key={f}><code>{f}</code></li>)}</ul><dl className={styles.proofFacts}>{content.durableProof.facts.map((f:any[])=><div key={f[0]}><dt>{f[0]}</dt><dd>{f[1]}</dd></div>)}</dl></div><footer>{content.durableProof.footer}</footer></div></section>
<section className={`${styles.section} ${styles.worksSection} ${styles.reveal}`}><div className={styles.sectionIntro}><p className={styles.kicker}>The worker stays replaceable</p><h2>{content.worksWith.title}</h2><p>{content.worksWith.text}</p></div><div className={styles.toolList}>{content.worksWith.tools.map((t:string)=><span key={t}>{t}</span>)}</div><a className={styles.textLink} href="/examples">Explore runnable examples</a></section>
<section className={`${styles.section} ${styles.finalCta} ${styles.reveal}`}><div><p className={styles.kicker}>Start locally</p><h2>{content.closing.title}</h2><p>{content.closing.text}</p></div><div className={styles.ctaGroup}><a className={styles.buttonPrimary} href={content.links.quickstart}>Run quickstart</a><CopyInstallButton location="closing"/><a className={styles.textLink} href={content.links.acr}>Inspect an Agent Change Record</a></div></section>
</main>}
